enum FpsStatus {
  NOT_COUNTING = "NOT_COUNTING",
  ABOUT_TO_START = "ABOUT_TO_START",
  WITHIN_THRESHOLD = "WITHIN_THRESHOLD",
  BELOW_THRESHOLD = "BELOW_THRESHOLD",
  ABOVE_THRESHOLD = "ABOVE_THRESHOLD",
}

export default FpsStatus;
