name: CI

on:
  push:
    branches:
      - "staging*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "25"

      - name: Install dependencies
        run: npm install

      - name: Run CI script
        run: npm run ci
