name: CI

on:
  push:
    branches:
      - "staging"
      - "staging/*"
      - "fix/ci-pipeline"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run CI script
        run: cat /home/runner/work/spiro/spiro/cypress.config.ts && npm run ci
